name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  helm:
    name: K8s chart test
    runs-on: ubuntu-latest

    steps:

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Lint
        run: |
          docker run --rm --interactive --network host \
              --name ct-lint \
              --volume $PWD:/workdir \
              --workdir /workdir/charts/shenyu \
              quay.io/helmpack/chart-testing:v3.4.0 sh -c 'helm dependency update \
               && cd ../.. \
               && helm repo add shenyu https://apache.github.io/incubator-shenyu-helm-chart \
               && ct lint \
                  --charts charts/shenyu '

      - name: fix permissions
        run: |
          sudo mkdir -p $HOME/.kube
          sudo chmod -R 777 $HOME/.kube




      - name: Test
        env:
          KIND_CLUSTER_NAME: kind
          SKIP_CLUSTER_CREATION: true
        run: |
          kind get kubeconfig > $HOME/.kube/kind-config-kind
          docker run --rm --interactive --network host \
              --name ct \
              --volume $HOME/.kube/kind-config-kind:/root/.kube/config \
              --volume $PWD:/workdir \
              --workdir /workdir/charts/shenyu \
              quay.io/helmpack/chart-testing:v3.4.0 sh -c 'helm dependency update \
               && cd ../.. \
               && helm repo add shenyu https://apache.github.io/incubator-shenyu-helm-chart \
               && ct install \
                  --charts charts/shenyu '