name: CI

on:
  push:

jobs:

  helm:
    name: K8s chart test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Helm tool installer
        uses: Azure/setup-helm@v3

      - name: Helm Chart Testing
        uses: helm/chart-testing-action@v2.2.1